version: 0.2
env:
  variables:
    PORT: 80
    REPOSITORY_URI: "769146158686.dkr.ecr.ap-south-1.amazonaws.com/web"

phases:
  phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 481974607063.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=481974607063.dkr.ecr.us-east-1.amazonaws.com/web
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:  
    commands:
      - echo Build started on `date`
      - echo building the docker image...
      - docker build -t $REPOSITORY_URI:latest . 

  post_build:
    commands:
      - echo build completed on `date`
      - echo Pushing the docker image...
      - docker push $REPOSITORY_URI:latest
      - aws ecs update-service --cluster web-cluster --service web-service --force-new-deployment
